# Generated by Django 5.2.6 on 2025-09-30 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelo', '0001_initial'),
        ('regional', '0001_initial'),
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfb', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('serie', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', unique=True)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('clave', models.CharField(blank=True, max_length=50, null=True)),
                ('admin', models.BooleanField(default=False)),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelo.modelo')),
                ('regional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regional.regional')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubicacion.ubicacion')),
            ],
            options={
                'verbose_name': 'Pdu',
                'verbose_name_plural': 'Pdus',
            },
        ),
    ]
