# Generated by Django 5.2.6 on 2025-10-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_usuario_apellidos_remove_usuario_nombres'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('TECNICO', 'Técnico'), ('USUARIO', 'Usuario')], default='USUARIO', max_length=20),
        ),
    ]
