# Generated by Django 5.2.6 on 2025-10-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cambiar_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
