# Generated by Django 5.2.6 on 2025-09-30 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciudad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Oficina Nacional', 'Oficina Nacional'), ('Sucursal', 'Sucursal'), ('Agencia', 'Agencia')], max_length=100)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciudad.ciudad')),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
    ]
