# Generated by Django 5.2.6 on 2025-10-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
