# Generated by Django 5.2.6 on 2025-09-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('La Paz', 'La Paz'), ('Tarija', 'Tarija'), ('Potosi', 'Potosí'), ('Santa Cruz', 'Santa Cruz'), ('Chuquisaca', 'Chuquisaca'), ('Cochabamba', 'Cochabamba'), ('Beni', 'Beni'), ('Oruro', 'Oruro'), ('Pando', 'Pando')], max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
    ]
