# Generated by Django 5.2.6 on 2025-10-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(choices=[('La Paz', 'La Paz'), ('Cochabamba', 'Cochabamba'), ('Santa Cruz', 'Santa Cruz'), ('Oruro', 'Oruro'), ('Potosi', 'Potosí'), ('Chuquisaca', 'Chuquisaca'), ('Tarija', 'Tarija'), ('Beni', 'Beni'), ('Pando', 'Pando')], max_length=100, unique=True),
        ),
    ]
